apiVersion: v1
kind: PersistentVolume
metadata:
  name: weaviate-pv
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 50Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: weaviate-data-weaviate-0
    namespace: weaviate
  nfs:
    path: /
    server: 192.168.9.129
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
